export type ErrorCodeType = ErrorCode | null;

enum ErrorCode {
  //CLIENT
  NO_NETWORK_CONNECTION = 'NO_NETWORK_CONNECTION',
  UNKNOWN = 'UNKNOWN',

  //API
  FIELD_INVALID = 'FIELD_INVALID',
  FIELD_REQUIRED = 'FIELD_REQUIRED',
  FIELD_NOT_NUMBER = 'FIELD_NOT_NUMBER',
  FIELD_NOT_BOOLEAN = 'FIELD_NOT_BOOLEAN',
  FIELD_NOT_ARRAY = 'FIELD_NOT_ARRAY',
  FIELD_MIN_LENGTH = 'FIELD_MIN_LENGTH',
  FIELD_DO_NOT_EXIST = 'FIELD_DO_NOT_EXIST',
  FIELD_HAS_DUPLICATES = 'FIELD_HAS_DUPLICATES',
  FIELD_NOT_ALLOWED = 'FIELD_NOT_ALLOWED',
  EMAIL_ADDRESS_INVALID = 'EMAIL_ADDRESS_INVALID',
  EMAIL_ADDRESS_EXISTS = 'EMAIL_ADDRESS_EXISTS',
  PHONE_NUMBER_INVALID = 'PHONE_NUMBER_INVALID',
  PHONE_NUMBER_EXISTS = 'PHONE_NUMBER_EXISTS',
  NAME_EXISTS = 'NAME_EXISTS',
  BARCODE_EXISTS = 'BARCODE_EXISTS',
  PASSWORD_LENGTH = 'PASSWORD_LENGTH',

  CREDENTIALS_INCORRECT = 'CREDENTIALS_INCORRECT',
  CREDENTIALS_MISSING = 'CREDENTIALS_MISSING',
  INVALID_TOKEN = 'INVALID_TOKEN',
  INVALID_TOKEN_PAYLOAD = 'INVALID_TOKEN_PAYLOAD',
  PERMISSION_DENIED = 'PERMISSION_DENIED',

  ID_NOT_NUMBER = 'ID_NOT_NUMBER',
  ID_DO_NOT_EXIST = 'ID_DO_NOT_EXIST',

  CUSTOMER_DO_NOT_EXIST = 'CUSTOMER_DO_NOT_EXIST',
  PRODUCT_DO_NOT_EXIST = 'PRODUCT_DO_NOT_EXIST',
  ADMINISTRATOR_DO_NOT_EXIST = 'ADMINISTRATOR_DO_NOT_EXIST',
  PHOTO_DO_NOT_EXIST = 'PHOTO_DO_NOT_EXIST',
  CATEGORY_DO_NOT_EXIST = 'CATEGORY_DO_NOT_EXIST',
  ORDER_DO_NOT_EXIST = 'ORDER_DO_NOT_EXIST',
  ORDER_ITEM_DO_NOT_EXIST = 'ORDER_ITEM_DO_NOT_EXIST',

  PHOTO_NAME_GENERATION_FAILED = 'PHOTO_NAME_GENERATION_FAILED',
  PHOTO_CATEGORY_ID_EXISTS = 'PHOTO_CATEGORY_ID_EXISTS',
  PHOTO_PRODUCT_ID_EXISTS = 'PHOTO_PRODUCT_ID_EXISTS',

  PRODUCT_OUT_OF_STOCK = 'PRODUCT_OUT_OF_STOCK',
}

export default ErrorCode;
